define INIT_BODY
;;; This file is auto generated by Makefile, do not edit!
(package-initialize)
(org-babel-load-file (expand-file-name "steel.org"
                   user-emacs-directory))

;; Also load the personal.org if exists for personal settings
(message (expand-file-name "personal.org" user-emacs-directory))

(if (file-exists-p (expand-file-name "personal.org"
	user-emacs-directory))
	(org-babel-load-file (expand-file-name "personal.org"
		user-emacs-directory))
(message "- personal.org not found, not loading.")
)
endef

export INIT_BODY

define PERSONAL_BODY
#+TITLE: Personal settings
#+OPTIONS: toc:nil
* Your own settings

Here you can specify local changes, such as paths, tweaks and more.
Changes here won't be overwritten when you do a fresh pull.

#+BEGIN_SRC emacs-lisp :tangle yes

;; elisp.code

#+END_SRC
endef
export PERSONAL_BODY



build:
	rm -f steel.el
	rm -f init.el
	rm -f personal.el
	rm -f .last-package-update-day
	@echo "$$INIT_BODY" > init.el
	@if [ ! -f personal.org ]; then \
		echo "$$PERSONAL_BODY" > personal.org; \
	fi
	mkdir -p .install-flags/
	emacs --script init.el

get-deps:
	pipx install basedpyright
	pipx install ruff
clean:
	rm -rf steel.el        \
	       personal.el     \
               .cache/         \
               eln-cache/      \
               url             \
               chatgpt/        \
               games/          \
               .install-flags  \
               transient/      \
               .chatgpt-shell.el \
               eshell          \
               elpa/           \
               projectile-bookmarks.eld \
               ac-comphist.dat \
               session.*       \
               tramp           \
               .lsp-session-v1 \
               auto-save-list/ \
               history         \
               tree-sitter/    \
               init.el
config:
	emacs steel.org
	build

