define INIT_BODY
;;; This file is auto generated by Makefile, do not edit!
(package-initialize)
(org-babel-load-file (expand-file-name "steel.org"
                   user-emacs-directory))
endef
export INIT_BODY


build:
	rm -f steel.el
	rm -f init.el
	@echo "$$INIT_BODY" > init.el
	emacs --script init.el
clean:
	rm -rf steel.el    \
               .cache      \
               eln-cache/  \
               recentf     \
               transient/  \
               elpa/       \
               projectile-bookmarks.eld \
               ac-comphist.dat \
               tramp           \
               auto-save-list  \
               init.el 
config:
	emacs steel.org
	build

